// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: platformd/checkpoint/v1alpha1/types.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointState int32

const (
	CheckpointState_RUNNING                     CheckpointState = 0
	CheckpointState_PULL_BASE_IMAGE_FAILED      CheckpointState = 1
	CheckpointState_CONTAINER_WAIT_READY_FAILED CheckpointState = 2
	CheckpointState_CONTAINER_CHECKPOINT_FAILED CheckpointState = 3
	CheckpointState_PUSH_CHECKPOINT_FAILED      CheckpointState = 4
	CheckpointState_COMPLETED                   CheckpointState = 5
)

// Enum value maps for CheckpointState.
var (
	CheckpointState_name = map[int32]string{
		0: "RUNNING",
		1: "PULL_BASE_IMAGE_FAILED",
		2: "CONTAINER_WAIT_READY_FAILED",
		3: "CONTAINER_CHECKPOINT_FAILED",
		4: "PUSH_CHECKPOINT_FAILED",
		5: "COMPLETED",
	}
	CheckpointState_value = map[string]int32{
		"RUNNING":                     0,
		"PULL_BASE_IMAGE_FAILED":      1,
		"CONTAINER_WAIT_READY_FAILED": 2,
		"CONTAINER_CHECKPOINT_FAILED": 3,
		"PUSH_CHECKPOINT_FAILED":      4,
		"COMPLETED":                   5,
	}
)

func (x CheckpointState) Enum() *CheckpointState {
	p := new(CheckpointState)
	*p = x
	return p
}

func (x CheckpointState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointState) Descriptor() protoreflect.EnumDescriptor {
	return file_platformd_checkpoint_v1alpha1_types_proto_enumTypes[0].Descriptor()
}

func (CheckpointState) Type() protoreflect.EnumType {
	return &file_platformd_checkpoint_v1alpha1_types_proto_enumTypes[0]
}

func (x CheckpointState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointState.Descriptor instead.
func (CheckpointState) EnumDescriptor() ([]byte, []int) {
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

type CheckpointStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// state of the current checkpointing process.
	State CheckpointState `protobuf:"varint,1,opt,name=state,proto3,enum=platformd.checkpoint.v1alpha1.CheckpointState" json:"state,omitempty"`
	// message provides details as to why the checkpoint is
	// in this state. this field is optional.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CheckpointStatus) Reset() {
	*x = CheckpointStatus{}
	mi := &file_platformd_checkpoint_v1alpha1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointStatus) ProtoMessage() {}

func (x *CheckpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_checkpoint_v1alpha1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointStatus.ProtoReflect.Descriptor instead.
func (*CheckpointStatus) Descriptor() ([]byte, []int) {
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointStatus) GetState() CheckpointState {
	if x != nil {
		return x.State
	}
	return CheckpointState_RUNNING
}

func (x *CheckpointStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_platformd_checkpoint_v1alpha1_types_proto protoreflect.FileDescriptor

var file_platformd_checkpoint_v1alpha1_types_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x72, 0x0a, 0x10, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x44,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xa7,
	0x01, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x50, 0x55, 0x4c, 0x4c, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x5f, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x43,
	0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b,
	0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x50,
	0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1a, 0x0a,
	0x16, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x50, 0x4f, 0x49, 0x4e, 0x54,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d,
	0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x05, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x73, 0x2f, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescOnce sync.Once
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescData = file_platformd_checkpoint_v1alpha1_types_proto_rawDesc
)

func file_platformd_checkpoint_v1alpha1_types_proto_rawDescGZIP() []byte {
	file_platformd_checkpoint_v1alpha1_types_proto_rawDescOnce.Do(func() {
		file_platformd_checkpoint_v1alpha1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_platformd_checkpoint_v1alpha1_types_proto_rawDescData)
	})
	return file_platformd_checkpoint_v1alpha1_types_proto_rawDescData
}

var file_platformd_checkpoint_v1alpha1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platformd_checkpoint_v1alpha1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_platformd_checkpoint_v1alpha1_types_proto_goTypes = []any{
	(CheckpointState)(0),     // 0: platformd.checkpoint.v1alpha1.CheckpointState
	(*CheckpointStatus)(nil), // 1: platformd.checkpoint.v1alpha1.CheckpointStatus
}
var file_platformd_checkpoint_v1alpha1_types_proto_depIdxs = []int32{
	0, // 0: platformd.checkpoint.v1alpha1.CheckpointStatus.state:type_name -> platformd.checkpoint.v1alpha1.CheckpointState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platformd_checkpoint_v1alpha1_types_proto_init() }
func file_platformd_checkpoint_v1alpha1_types_proto_init() {
	if File_platformd_checkpoint_v1alpha1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platformd_checkpoint_v1alpha1_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platformd_checkpoint_v1alpha1_types_proto_goTypes,
		DependencyIndexes: file_platformd_checkpoint_v1alpha1_types_proto_depIdxs,
		EnumInfos:         file_platformd_checkpoint_v1alpha1_types_proto_enumTypes,
		MessageInfos:      file_platformd_checkpoint_v1alpha1_types_proto_msgTypes,
	}.Build()
	File_platformd_checkpoint_v1alpha1_types_proto = out.File
	file_platformd_checkpoint_v1alpha1_types_proto_rawDesc = nil
	file_platformd_checkpoint_v1alpha1_types_proto_goTypes = nil
	file_platformd_checkpoint_v1alpha1_types_proto_depIdxs = nil
}
