package space.chunks.visual.text

object MinecraftNormalFontMetrics : VisualFontMetrics {
    private val charMap: Map<Char, VisualCharInfo> = mapOf(
        'A' to VisualCharInfo('A', 5),
        'B' to VisualCharInfo('B', 5),
        'C' to VisualCharInfo('C', 5),
        'D' to VisualCharInfo('D', 5),
        'E' to VisualCharInfo('E', 5),
        'F' to VisualCharInfo('F', 5),
        'G' to VisualCharInfo('G', 5),
        'H' to VisualCharInfo('H', 5),
        'I' to VisualCharInfo('I', 3),
        'J' to VisualCharInfo('J', 5),
        'K' to VisualCharInfo('K', 5),
        'L' to VisualCharInfo('L', 5),
        'M' to VisualCharInfo('M', 5),
        'N' to VisualCharInfo('N', 5),
        'O' to VisualCharInfo('O', 5),
        'P' to VisualCharInfo('P', 5),
        'Q' to VisualCharInfo('Q', 5),
        'R' to VisualCharInfo('R', 5),
        'S' to VisualCharInfo('S', 5),
        'T' to VisualCharInfo('T', 5),
        'U' to VisualCharInfo('U', 5),
        'V' to VisualCharInfo('V', 5),
        'W' to VisualCharInfo('W', 5),
        'X' to VisualCharInfo('X', 5),
        'Y' to VisualCharInfo('Y', 5),
        'Z' to VisualCharInfo('Z', 5),
        'a' to VisualCharInfo('a', 5),
        'b' to VisualCharInfo('b', 5),
        'c' to VisualCharInfo('c', 5),
        'd' to VisualCharInfo('d', 5),
        'e' to VisualCharInfo('e', 5),
        'f' to VisualCharInfo('f', 4),
        'g' to VisualCharInfo('g', 5),
        'h' to VisualCharInfo('h', 5),
        'i' to VisualCharInfo('i', 1),
        'j' to VisualCharInfo('j', 5),
        'k' to VisualCharInfo('k', 4),
        'l' to VisualCharInfo('l', 1),
        'm' to VisualCharInfo('m', 5),
        'n' to VisualCharInfo('n', 5),
        'o' to VisualCharInfo('o', 5),
        'p' to VisualCharInfo('p', 5),
        'q' to VisualCharInfo('q', 5),
        'r' to VisualCharInfo('r', 5),
        's' to VisualCharInfo('s', 5),
        't' to VisualCharInfo('t', 3),
        'u' to VisualCharInfo('u', 5),
        'v' to VisualCharInfo('v', 5),
        'w' to VisualCharInfo('w', 5),
        'x' to VisualCharInfo('x', 5),
        'y' to VisualCharInfo('y', 5),
        'z' to VisualCharInfo('z', 5),
        '0' to VisualCharInfo('0', 5),
        '1' to VisualCharInfo('1', 5),
        '2' to VisualCharInfo('2', 5),
        '3' to VisualCharInfo('3', 5),
        '4' to VisualCharInfo('4', 5),
        '5' to VisualCharInfo('5', 5),
        '6' to VisualCharInfo('6', 5),
        '7' to VisualCharInfo('7', 5),
        '8' to VisualCharInfo('8', 5),
        '9' to VisualCharInfo('9', 5),
        '!' to VisualCharInfo('!', 1),
        '@' to VisualCharInfo('@', 6),
        '#' to VisualCharInfo('#', 5),
        '$' to VisualCharInfo('$', 5),
        '%' to VisualCharInfo('%', 5),
        '^' to VisualCharInfo('^', 5),
        '&' to VisualCharInfo('&', 5),
        '*' to VisualCharInfo('*', 5),
        '(' to VisualCharInfo('(', 4),
        ')' to VisualCharInfo(')', 4),
        '-' to VisualCharInfo('-', 5),
        '_' to VisualCharInfo('_', 5),
        '+' to VisualCharInfo('+', 5),
        '=' to VisualCharInfo('=', 5),
        '{' to VisualCharInfo('{', 4),
        '}' to VisualCharInfo('}', 4),
        '[' to VisualCharInfo('[', 3),
        ']' to VisualCharInfo(']', 3),
        ':' to VisualCharInfo(':', 1),
        ';' to VisualCharInfo(';', 1),
        '"' to VisualCharInfo('"', 3),
        '\'' to VisualCharInfo('\'', 1),
        '<' to VisualCharInfo('<', 4),
        '>' to VisualCharInfo('>', 4),
        '?' to VisualCharInfo('?', 5),
        '/' to VisualCharInfo('/', 5),
        '\\' to VisualCharInfo('\\', 5),
        '|' to VisualCharInfo('|', 1),
        '~' to VisualCharInfo('~', 5),
        '`' to VisualCharInfo('`', 2),
        '.' to VisualCharInfo('.', 1),
        ',' to VisualCharInfo(',', 1),
        ' ' to VisualCharInfo(' ', 3),
    )

    private val defaultChar = VisualCharInfo('\u0000', 0)

    override fun charInfo(char: Char): VisualCharInfo =
        charMap[char] ?: defaultChar

    override fun width(content: String): Int {
        if (content.isEmpty()) {
            return 0
        }

        return content.sumOf { charInfo(it).effectiveWidth + 1 } - 1
    }
}
