//
//Chunk Explorer, a platform for hosting and discovering Minecraft servers.
//Copyright (C) 2025 Yannic Rieger <oss@76k.io>
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU Lesser General Public
//License as published by the Free Software Foundation; either
//version 3 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//Lesser General Public License for more details.
//
//You should have received a copy of the GNU Lesser General Public License
//along with this program; if not, write to the Free Software Foundation,
//Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: platformd/workload/v1alpha2/api.proto

package v1alpha2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WorkloadStatusRequest) Reset() {
	*x = WorkloadStatusRequest{}
	mi := &file_platformd_workload_v1alpha2_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatusRequest) ProtoMessage() {}

func (x *WorkloadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_workload_v1alpha2_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkloadStatusRequest) Descriptor() ([]byte, []int) {
	return file_platformd_workload_v1alpha2_api_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkloadStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *WorkloadStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WorkloadStatusResponse) Reset() {
	*x = WorkloadStatusResponse{}
	mi := &file_platformd_workload_v1alpha2_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatusResponse) ProtoMessage() {}

func (x *WorkloadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platformd_workload_v1alpha2_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkloadStatusResponse) Descriptor() ([]byte, []int) {
	return file_platformd_workload_v1alpha2_api_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadStatusResponse) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_platformd_workload_v1alpha2_api_proto protoreflect.FileDescriptor

var file_platformd_workload_v1alpha2_api_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2f, 0x77, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x32, 0x1a, 0x27, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a,
	0x15, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x16, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x8c, 0x01, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x0e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x2e, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x33, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x2f, 0x65,
	0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x64, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platformd_workload_v1alpha2_api_proto_rawDescOnce sync.Once
	file_platformd_workload_v1alpha2_api_proto_rawDescData = file_platformd_workload_v1alpha2_api_proto_rawDesc
)

func file_platformd_workload_v1alpha2_api_proto_rawDescGZIP() []byte {
	file_platformd_workload_v1alpha2_api_proto_rawDescOnce.Do(func() {
		file_platformd_workload_v1alpha2_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_platformd_workload_v1alpha2_api_proto_rawDescData)
	})
	return file_platformd_workload_v1alpha2_api_proto_rawDescData
}

var file_platformd_workload_v1alpha2_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platformd_workload_v1alpha2_api_proto_goTypes = []any{
	(*WorkloadStatusRequest)(nil),  // 0: platformd.workload.v1alpha2.WorkloadStatusRequest
	(*WorkloadStatusResponse)(nil), // 1: platformd.workload.v1alpha2.WorkloadStatusResponse
	(*WorkloadStatus)(nil),         // 2: platformd.workload.v1alpha2.WorkloadStatus
}
var file_platformd_workload_v1alpha2_api_proto_depIdxs = []int32{
	2, // 0: platformd.workload.v1alpha2.WorkloadStatusResponse.status:type_name -> platformd.workload.v1alpha2.WorkloadStatus
	0, // 1: platformd.workload.v1alpha2.WorkloadService.WorkloadStatus:input_type -> platformd.workload.v1alpha2.WorkloadStatusRequest
	1, // 2: platformd.workload.v1alpha2.WorkloadService.WorkloadStatus:output_type -> platformd.workload.v1alpha2.WorkloadStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platformd_workload_v1alpha2_api_proto_init() }
func file_platformd_workload_v1alpha2_api_proto_init() {
	if File_platformd_workload_v1alpha2_api_proto != nil {
		return
	}
	file_platformd_workload_v1alpha2_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platformd_workload_v1alpha2_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platformd_workload_v1alpha2_api_proto_goTypes,
		DependencyIndexes: file_platformd_workload_v1alpha2_api_proto_depIdxs,
		MessageInfos:      file_platformd_workload_v1alpha2_api_proto_msgTypes,
	}.Build()
	File_platformd_workload_v1alpha2_api_proto = out.File
	file_platformd_workload_v1alpha2_api_proto_rawDesc = nil
	file_platformd_workload_v1alpha2_api_proto_goTypes = nil
	file_platformd_workload_v1alpha2_api_proto_depIdxs = nil
}
