//
//Chunk Explorer, a platform for hosting and discovering Minecraft servers.
//Copyright (C) 2025 Yannic Rieger <oss@76k.io>
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU Lesser General Public
//License as published by the Free Software Foundation; either
//version 3 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//Lesser General Public License for more details.
//
//You should have received a copy of the GNU Lesser General Public License
//along with this program; if not, write to the Free Software Foundation,
//Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: platformd/workload/v1alpha2/api.proto

package v1alpha2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadService_WorkloadStatus_FullMethodName = "/platformd.workload.v1alpha2.WorkloadService/WorkloadStatus"
)

// WorkloadServiceClient is the client API for WorkloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadServiceClient interface {
	WorkloadStatus(ctx context.Context, in *WorkloadStatusRequest, opts ...grpc.CallOption) (*WorkloadStatusResponse, error)
}

type workloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadServiceClient(cc grpc.ClientConnInterface) WorkloadServiceClient {
	return &workloadServiceClient{cc}
}

func (c *workloadServiceClient) WorkloadStatus(ctx context.Context, in *WorkloadStatusRequest, opts ...grpc.CallOption) (*WorkloadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStatusResponse)
	err := c.cc.Invoke(ctx, WorkloadService_WorkloadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadServiceServer is the server API for WorkloadService service.
// All implementations must embed UnimplementedWorkloadServiceServer
// for forward compatibility.
type WorkloadServiceServer interface {
	WorkloadStatus(context.Context, *WorkloadStatusRequest) (*WorkloadStatusResponse, error)
	mustEmbedUnimplementedWorkloadServiceServer()
}

// UnimplementedWorkloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadServiceServer struct{}

func (UnimplementedWorkloadServiceServer) WorkloadStatus(context.Context, *WorkloadStatusRequest) (*WorkloadStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkloadStatus not implemented")
}
func (UnimplementedWorkloadServiceServer) mustEmbedUnimplementedWorkloadServiceServer() {}
func (UnimplementedWorkloadServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadServiceServer will
// result in compilation errors.
type UnsafeWorkloadServiceServer interface {
	mustEmbedUnimplementedWorkloadServiceServer()
}

func RegisterWorkloadServiceServer(s grpc.ServiceRegistrar, srv WorkloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadService_ServiceDesc, srv)
}

func _WorkloadService_WorkloadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).WorkloadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_WorkloadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).WorkloadStatus(ctx, req.(*WorkloadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadService_ServiceDesc is the grpc.ServiceDesc for WorkloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platformd.workload.v1alpha2.WorkloadService",
	HandlerType: (*WorkloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkloadStatus",
			Handler:    _WorkloadService_WorkloadStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platformd/workload/v1alpha2/api.proto",
}
